mi_cdn_redirect:
    pattern: /{path}
    host: "{subdomain}.majdn.com"
    defaults: { _controller: MajoredInMainBundle:Redirect:index }
    requirements:
        path: ".*"
       
mi_main_sitemap_index:
    pattern: /sitemaps/index.{_format}
    defaults: { _controller: MajoredInMainBundle:SiteMapXml:index }
    requirements:
        _format:  xml
        
mi_main_sitemap_locations:
    pattern: /sitemaps/locations.{_format}
    defaults: { _controller: MajoredInMainBundle:SiteMapXml:locations }
    requirements:
        _format:  xml
        
mi_main_sitemap_majors:
    pattern: /sitemaps/majors/{id}.{_format}
    defaults: { _controller: MajoredInMainBundle:SiteMapXml:majors }
    requirements:
        _format:  xml