parameters:
#    majored_in_main.example.class: MajoredIn\MainBundle\Example

services:
#    majored_in_main.example:
#        class: %majored_in_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
