imports:
    - { resource: config.yml }
    
framework:
    templating: 
        assets_base_urls:
            http:   ['http://www.majoredin.com']
            ssl:    ['https://www.majoredin.com']

doctrine:
    orm:
        metadata_cache_driver:
            type: %memcached_driver%
            host: %memcached_host%
            port: %memcached_port%
        query_cache_driver:
            type: %memcached_driver%
            host: %memcached_host%
            port: %memcached_port%
        result_cache_driver:
            type: %memcached_driver%
            host: %memcached_host%
            port: %memcached_port%
            
liip_doctrine_cache:
    namespaces:
        precache:
            namespace: mi_precache
            type: %memcached_driver%
            host: %memcached_host%
            port: %memcached_port%
        autocomplete:
            namespace: mi_autocomplete
            type: %memcached_driver%
            host: %memcached_host%
            port: %memcached_port%
        layout:
            namespace: mi_layout
            type: %memcached_driver%
            host: %memcached_host%
            port: %memcached_port%
        majorguide:
            namespace: mi_majorguide
            type: %memcached_driver%
            host: %memcached_host%
            port: %memcached_port%

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            