imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version: %assets_version%, assets_version_format: %%s?ver=%%s }
    default_locale:  %locale%
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      "%kernel.root_dir%/../web-src"
    write_to:       "%kernel.root_dir%/../web"
    #bundles:        [ ]
    java: %java_exe%
    filters:
        cssrewrite: ~
        closure:
            jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                slaves:
                    slave1:
                        host:     %slave_host%
                        port:     %slave_port%
                        dbname:   %database_name%
                        user:     %database_user%
                        password: %database_password%
                        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        
# Wordpress Bootstrap
majored_in_wordpress:
    install_path:     %kernel.root_dir%/../web/cms
    
    database:
        master:
            host:     %database_host%
            port:     %database_port%
            dbname:   %database_name%
            user:     %database_user%
            password: %database_password%
            charset:  UTF8
        slave:
            host:     %slave_host%
            port:     %slave_port%
            dbname:   %database_name%
            user:     %database_user%
            password: %database_password%
            charset:  UTF8
            
    auth_key:         %wp_auth_key%
    secure_auth_key:  %wp_secure_auth_key%
    logged_in_key:    %wp_logged_in_key%
    nonce_key:        %wp_nonce_key%
    auth_salt:        %wp_auth_salt%
    secure_auth_salt: %wp_secure_auth_salt%
    logged_in_salt:   %wp_logged_in_salt%
    nonce_salt:       %wp_nonce_salt%
    
    table_prefix:     %wp_table_prefix%

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
