imports:
    - { resource: config.yml }
    
framework:
    templating: 
        assets_base_urls:
            http:   ['http://cdn1.majdn.com']
            ssl:    ['https://www.majoredin.com']

doctrine:
    orm:
        metadata_cache_driver: apc
        query_cache_driver: apc
        result_cache_driver:
            type: %memcached_driver%
            host: %memcached_host%
            port: %memcached_port%

#Get the absolute hostnames in twig for switch URLs
twig:
    globals: 
        full_host: http://www.majoredin.com
        mobile_host: http://m.majoredin.com
        
mobile_detect:
    redirect:
        mobile:
            is_enabled: false
            host: http://m.majoredin.com
            action: no_redirect

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
