imports:
    - { resource: config_dev.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_mobile_dev.yml" }

mobile_detect:
    redirect:
        mobile:
            is_enabled: false