MajoredInMainBundle:
    resource: "@MajoredInMainBundle/Resources/config/routing_mobile.yml"

MajoredInJobSearchBundle:
    resource: "@MajoredInJobSearchBundle/Resources/config/routing_mobile.yml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
