#mi_search.feed_reader.curlopts declared in config.yml

parameters:
    mi_search.feed_reader.curlopts:
        CURLOPT_HEADER: false
        CURLOPT_RETURNTRANSFER: true
        CURLOPT_FOLLOWLOCATION: true
        CURLOPT_MAXREDIRS: 3
        CURLOPT_CONNECTTIMEOUT: 2
        CURLOPT_TIMEOUT: 10

services:
    mi_search.feed_reader:
        class: MajoredIn\JobSearchBundle\Util\FeedReader
        arguments:
            - %mi_search.feed_reader.curlopts%