mi_jobs_results:
    pattern:  /jobs/{major}/{location}
    defaults: { _controller: MajoredInJobSearchBundle:JobSearch:results, location: everywhere }

# Changes to this must also be in jobs-api.js
mi_jobs_api_results:
    pattern:  /jobs-api/v1/{major}/{location}
    defaults: { _controller: MajoredInJobSearchBundle:JobSearch:resultsApi, location: everywhere }
    
mi_jobs_precache:
    pattern:  /precache/{major}/{location}
    defaults: { _controller: MajoredInJobSearchBundle:JobSearch:preCache, location: everywhere }
    
mi_jobs_redirect:
    pattern: /jobs
    defaults: { _controller: MajoredInJobSearchBundle:JobSearch:redirect }
    methods: [POST]

#TODO: MAKE CONTROLLER FOR THIS  
mi_jobs_landing:
    pattern: /jobs
    defaults: { _controller: MajoredInJobSearchBundle:JobSearch:redirect }
    methods: [GET]
    
mi_jobs_advanced_submit:
    pattern: /advanced-search
    defaults: { _controller: MajoredInJobSearchBundle:Advanced:submit }
        
mi_autocomplete_major:
    pattern: /autocomplete/major
    defaults: { _controller: MajoredInJobSearchBundle:AutoComplete:major }
    
mi_autocomplete_location:
    pattern: /autocomplete/location
    defaults: { _controller: MajoredInJobSearchBundle:AutoComplete:location }