parameters:
    mi_search.job_query.base_url: http://api.simplyhired.com/a/jobs-api/xml-v2

    mi_search.job_query.allowable_params:
        dist:
            translation: mi
            requirements: /^([1-9]\d*|exact)$/
        page:
            translation: pn
            requirements: /^[1-9]\d*$/
        date:
            translation: fdb
            requirements: /^[1-9]\d*$/
        sort:
            translation: sb
            requirements: /^(rd|ra|dd|da|td|ta|cd|ca|ld|la)$/
        jobtype:
            translation: fjt
            requirements: /^(full-time|part-time|internship)$/
        boards:
            translation: fsr
            requirements: /^(primary|job_board)$/
        recruiters:
            translation: fem
            requirements: /^(employer|recruiter)$/
        size:
            translation: fcz
            requirements: /^(1|2|3|4|5|6)$/
        revenue:
            translation: fcr
            requirements: /^(1|2|3|4|5|6)$/
        all:
            translation: qa
            requirements: /^.+$/
        exact:
            translation: qe
            requirements: /^.+$/
        atleast:
            translation: qo
            requirements: /^.+$/
        without:
            translation: qw
            requirements: /^.+$/
        title:
            translation: t
            requirements: /^.+$/
        company:
            translation: c
            requirements: /^.+$/
        hidden:
            translation: clst
            requirements: /^comboxp0$/
            
    mi_search.job_query.publisher_id: 91234
    mi_search.job_query.authkey: 137a466c686b7a13024d1e35cfa9dfecce72dc23.91234
    mi_search.job_query.search_style: 2
    mi_search.job_query.configuration_flag: r

services:
    mi_search.job_query.factory:
        class: MajoredIn\JobSearchBundle\Search\JobQueryFactory
        arguments:
            - @mi_search.major.manager
            - @mi_search.major_alias.manager
            - %mi_search.job_query.base_url%
            - %mi_search.job_query.allowable_params%
            - %mi_search.job_query.publisher_id%
            - %mi_search.job_query.authkey%
            - %mi_search.job_query.search_style%
            - %mi_search.job_query.configuration_flag%
            
